#: import get_color_from_hex kivy.utils.get_color_from_hex

<TestPage>:
    MDScreen:
        name: "home"
        MDLabel:
            text: "Home of message board"
            halign: "center"
        MDBoxLayout:
            size_hint_y:None
            size_hint_x: 1
            height: "65dp"
            spacing: "10dp"
            padding: "12dp", 0, "12dp", 0

            canvas.before:
                Color:
                    rgb: get_color_from_hex("#f0f0f0")
                Rectangle:
                    source: "./bg.jpg"
                    pos: self.pos
                    size: self.size
            FloatLayout:
                pos_hint: {"center_x": .5}
                MDIconButton:
                    icon: "home"
                    size_hint: None, None
                    pos_hint: {"center_y": .5,"center_x": .3}
                    on_release: root.current = "home"
                MDIconButton:
                    icon: "chat"
                    pos_hint: {"center_y": .5,"center_x": .5}
                    on_release: root.current = "chats"
                MDIconButton:
                    icon: "account-multiple"
                    pos_hint: {"center_y": .5,"center_x": .7}
                    on_release: root.current = "contact"

    MDScreen:
        name: "chats"
        MDLabel:
            text: "Chats of user"
            halign: "center"
        MDBoxLayout:
            size_hint_y:None
            size_hint_x: 1
            height: "65dp"
            spacing: "10dp"
            padding: "12dp", 0, "12dp", 0

            canvas.before:
                Color:
                    rgb: get_color_from_hex("#f0f0f0")
                Rectangle:
                    source: "./bg.jpg"
                    pos: self.pos
                    size: self.size
            FloatLayout:
                pos_hint: {"center_x": .5}
                MDIconButton:
                    icon: "home"
                    size_hint: None, None
                    pos_hint: {"center_y": .5,"center_x": .3}
                    on_release: root.current = "home"
                MDIconButton:
                    icon: "chat"
                    pos_hint: {"center_y": .5,"center_x": .5}
                    on_release: root.current = "chats"
                MDIconButton:
                    icon: "account-multiple"
                    pos_hint: {"center_y": .5,"center_x": .7}
                    on_release: root.current = "contact"
    MDScreen:
        name: "contact"
        MDLabel:
            text: "Contacts of user"
            halign: "center"
        MDBoxLayout:
            size_hint_y:None
            size_hint_x: 1
            height: "65dp"
            spacing: "10dp"
            padding: "12dp", 0, "12dp", 0

            canvas.before:
                Color:
                    rgb: get_color_from_hex("#f0f0f0")
                Rectangle:
                    source: "./bg.jpg"
                    pos: self.pos
                    size: self.size
            FloatLayout:
                pos_hint: {"center_x": .5}
                MDIconButton:
                    icon: "home"
                    size_hint: None, None
                    pos_hint: {"center_y": .5,"center_x": .3}
                    on_release: root.current = "home"
                MDIconButton:
                    icon: "chat"
                    pos_hint: {"center_y": .5,"center_x": .5}
                    on_release: root.current = "chats"
                MDIconButton:
                    icon: "account-multiple"
                    pos_hint: {"center_y": .5,"center_x": .7}
                    on_release: root.current = "contact"

    